// <auto-generated />
namespace RentACar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class StatusAddedToModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StatusAddedToModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201909190730208_StatusAddedToModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
